# yaml-language-server: $schema=https://raw.githubusercontent.com/oxy-hq/oxy/refs/heads/main/json-schemas/config.json
defaults:
  database: motherduck
models:
  - vendor: openai
    name: openai
#    model_ref: gpt-5.2
    model_ref: gpt-5.4
    key_var: OPENAI_API_KEY
    api_url: https://api.openai.com/v1
  - vendor: anthropic
    name: claude
    model_ref: claude-haiku-4-5
    key_var: ANTHROPIC_API_KEY
databases:
  - name: motherduck
    type: motherduck
    token_var: MOTHERDUCK_PERSONAL_TOKEN
    database: personal_data
    schemas:
      exercise:
      - "*"
      body:
      - "*"
      nutrition:
      - "*"
mcp:
  tools:
    - semantics/topics/*.topic.yml


builder_agent:
  model: claude